text = ((trace) 'EOL')+ 'EOF';
trace = (dots) ((line) 'EOL' (dots))+;
dots = ['...' 'EOL'] ;
line = (parallel) | (annotation) | (comment) ;
comment = '///' (any character unteil EOL)* ;
annotation = '//' (label) ;
parallel = (element) ('|' (element) )*;
element = [(role)] ((task) | (event) | (XORlabel) | (data)) | (role);
role = (label) ':' ;
XORlabel = (label) '?' ;
task = [(ttype)] (label);
event = '(' [(etype) | (ibetype)] (label) ')' | '((' (betype) (label '))';
ttype = ('send' | 'receive' | 'user' | 'manual' | 'service' | 'script' | 'rule' ) ;
etype = ('start' | 'finish' | 'timer' | 'send' | 'receive' | 'publish' | 'notify' | 'error' | 'escalate' | 'terminate' ) ;
ibetype = ('deadline' | 'exception' | 'received' | 'escalated' ) ;
betype = ('deadline' | 'received' | 'escalated' ) ;
data = '[' [(dtype)] (label) ']' | [(dtype)] (label) '[' (labelstate) ']' ;
dtype = ('db') ;
labelstate = (label) ;
label = (String)
